FROM node:24-slim@sha256:242549cd46785b480c832479a730f4f2a20865d61ea2e404fdb2a5c3d3b73ecf

ENV CI=true
ENV PNPM_HOME=/pnpm
ENV PATH=/pnpm:$PATH

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.33.0 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/indexer/package.json apps/indexer/package.json
COPY apps/metrics-api/package.json apps/metrics-api/package.json
COPY apps/metrics-publisher/package.json apps/metrics-publisher/package.json
COPY apps/client/package.json apps/client/package.json
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm run build

USER node

EXPOSE 3000
CMD ["pnpm", "--dir", "apps/metrics-api", "start"]
